# fly.toml app configuration file generated for hello-world-app-weathered-darkness-5919 on 2024-10-04T16:12:24+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hello-world-app-weathered-darkness-5919'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
